version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: cinecorner-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinecorner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
    driver: local
